version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    environment:
    - MONGO_INITDB_DATABASE=insurance
    volumes:
    - ./mongodb-data:/data/db
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
    - backend-network
  backend:
    build: ./api
    container_name: api
    ports:
    - 7000:7000
    volumes:
    - ./api:/app
    restart: unless-stopped
    depends_on:
    - mongodb
    networks:
    - backend-network
  frontend:
    build: ./web
    container_name: web
    ports:
    - 5173:5173
    volumes:
    - ./web:/app
    restart: unless-stopped
    depends_on:
    - backend
    networks:
    - backend-network

volumes:
  mongodb-data:
  api:
  web:

networks:
  backend-network: